name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up environment
        run: echo "APP_SECRET=${{ secrets.APP_SECRET }}" >> $GITHUB_ENV

      - name: Generate config
        run: ./TheIgloo2.0/TheApp/generate-config.sh
